<?php
class caratula extends MY_Model {
	function __construct()
	{
            parent::__construct();
	}
	
        public function getFields(){
            return array(array('UBIGEO', 'render' => TRUE, 'type' => 'TEXT', 'length' => '6')
,array('ZONA', 'render' => TRUE, 'type' => 'TEXT', 'length' => '5','primary_key' => TRUE)
,array('SECCION', 'render' => TRUE, 'type' => 'TEXT', 'length' => '3','primary_key' => TRUE)
,array('MANZANA', 'render' => TRUE, 'type' => 'TEXT', 'length' => '4')
,array('ESTADO_ENVIO', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'radio'=>TRUE, 'options'=>array('' => '1 ABIERTO','' => '2 CERRADO'))
,array('AREA', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'radio'=>TRUE, 'options'=>array('1' => '1. URBANO','2' => '2. RURAL'))
,array('ID', 'render' => TRUE, 'type' => 'TEXT', 'length' => '7')
,array('VIVIENDA', 'render' => TRUE, 'type' => 'TEXT', 'length' => '4','primary_key' => TRUE)
,array('CCDD', 'render' => TRUE, 'type' => 'TEXT', 'length' => '2','primary_key' => TRUE)
,array('NOMBREDD', 'render' => TRUE, 'type' => 'TEXT', 'length' => '50')
,array('CCPP', 'render' => TRUE, 'type' => 'TEXT', 'length' => '2','primary_key' => TRUE)
,array('NOMBREPV', 'render' => TRUE, 'type' => 'TEXT', 'length' => '50')
,array('CCDI', 'render' => TRUE, 'type' => 'TEXT', 'length' => '2','primary_key' => TRUE)
,array('NOMBREDI', 'render' => TRUE, 'type' => 'TEXT', 'length' => '50')
,array('CODCCPP', 'render' => TRUE, 'type' => 'TEXT', 'length' => '4')
,array('NOMCCPP', 'render' => TRUE, 'type' => 'TEXT', 'length' => '30')
,array('ZONA_ID', 'render' => TRUE, 'type' => 'TEXT', 'length' => '3')
,array('ZONA_A', 'render' => TRUE, 'type' => 'TEXT', 'length' => '1')
,array('SECCION_U', 'render' => TRUE, 'type' => 'TEXT', 'length' => '3')
,array('AEU', 'render' => TRUE, 'type' => 'TEXT', 'length' => '3','primary_key' => TRUE)
,array('MANZANA_ID', 'render' => TRUE, 'type' => 'TEXT', 'length' => '3')
,array('MANZANA_A', 'render' => TRUE, 'type' => 'TEXT', 'length' => '1')
,array('FRENTE', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '2')
,array('SECCION_R', 'render' => TRUE, 'type' => 'TEXT', 'length' => '3')
,array('AER_INI', 'render' => TRUE, 'type' => 'TEXT', 'length' => '3','primary_key' => TRUE)
,array('AER_FIN', 'render' => TRUE, 'type' => 'TEXT', 'length' => '3','primary_key' => TRUE)
,array('TIPVIA', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'dropdown'=>TRUE, 'options'=>array('' => 'SELECCIONE','1' => '1. AVENIDA','2' => '2. CALLE','3' => '3. JIRóN','4' => '4. PASAJE','5' => '5. CARRETERA','6' => '6. OTRO'))
,array('NOMVIA', 'render' => TRUE, 'type' => 'TEXT', 'length' => '30')
,array('NROPTA', 'render' => TRUE, 'type' => 'TEXT', 'length' => '4')
,array('NROPTA_ALF', 'render' => TRUE, 'type' => 'TEXT', 'length' => '1')
,array('BLOCK', 'render' => TRUE, 'type' => 'TEXT', 'length' => '6')
,array('INTERIOR', 'render' => TRUE, 'type' => 'TEXT', 'length' => '4')
,array('INTERIOR_ALF', 'render' => TRUE, 'type' => 'TEXT', 'length' => '1')
,array('PISO', 'render' => TRUE, 'type' => 'TEXT', 'length' => '2')
,array('MZA', 'render' => TRUE, 'type' => 'TEXT', 'length' => '5')
,array('LOTE', 'render' => TRUE, 'type' => 'TEXT', 'length' => '4')
,array('KM', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '6')
,array('GPS_LONG', 'render' => TRUE, 'type' => 'TEXT', 'length' => '20')
,array('GPS_LATI', 'render' => TRUE, 'type' => 'TEXT', 'length' => '20')
,array('THOGAR', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '2')
,array('HOGAR', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '2')
,array('C2_P1', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '2', 'dropdown'=>TRUE, 'options'=>array('' => 'SELECCIONE','VIVIENDA PARTICULAR 
1' => 'VIVIENDA PARTICULAR 
1. CASA INDEPENDIENTE','2' => '2. DEPARTAMENTO EN EDIFICIO','3' => '3. VIVIENDA EN QUINTA','4' => '4. VIVIENDA EN CASA DE VECINDAD (CALLEJóN, SOLAR O CORRALóN)','5' => '5. CHOZA O CABAñA','6' => '6. VIVIENDA IMPROVISADA','7' => '7. LOCAL NO DESTINADO PARA HABITACIóN HUMANA','8' => '8. OTRO TIPO','VIVIENDA COLECTIVA 
9' => 'VIVIENDA COLECTIVA 
9. HOTEL, HOSTAL, HOSPEDAJE, CASA PENSIóN','10' => '10. ESTABLECIMIENTO DE SALUD','11' => '11. ESTABLECIMIENTO PENITENCIARIO','12' => '12. CENTRO DE ATENCIóN RESIDENCIAL PARA ADULTOS MAYORES','13' => '13. CENTRO DE ATENCIóN RESIDENCIAL PARA NIñAS/OS Y ADOLESCENTES','14' => '14. CONVENTOS, MONASTERIOS O SIMILARES','15' => '15. CUARTEL, CAMPAMENTO, BASE DE FF.AA. O PNP.','16' => '16. OTRO','OTRO TIPO 
17' => 'OTRO TIPO 
17. EN LA CALLE (PERSONAS SIN VIVIENDA)','18' => '18. GARITA, PUERTO, AEROPUERTO O SIMILARES'))
,array('C2_P1_O', 'render' => TRUE, 'type' => 'TEXT', 'length' => '25')
,array('C2_P2', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'dropdown'=>TRUE, 'options'=>array('' => 'SELECCIONE','OCUPADA 
1' => 'OCUPADA 
1. CON PERSONAS PRESENTES','2' => '2. CON PERSONAS AUSENTES','3' => '3. DE USO OCASIONAL','DESOCUPADA 
4' => 'DESOCUPADA 
4. EN ALQUILER O VENTA','5' => '5. EN CONSTRUCCIóN O REPARACIóN','6' => '6. ABANDONADA O CERRADA','7' => '7. OTRA CAUSA'))
,array('C2_P3', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '2', 'dropdown'=>TRUE, 'options'=>array('' => 'SELECCIONE','1' => '1. LADRILLO O BLOQUE DE CEMENTO?','2' => '2. PIEDRA O SILLAR CON CAL O CEMENTO?','3' => '3. ADOBE?','4' => '4. TAPIA?','5' => '5. QUINCHA (CAñA CON BARRO)?','6' => '6. PIEDRA CON BARRO?','7' => '7. MADERA (PONA, TORNILLO, ETC?','8' => '8. TRIPLAY / CALAMINA / ESTERA ?','9' => '9. OTRO MATERIAL?'))
,array('C2_P3_O', 'render' => TRUE, 'type' => 'TEXT', 'length' => '15')
,array('C2_P4', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'dropdown'=>TRUE, 'options'=>array('' => 'SELECCIONE','1' => '1. CONCRETO ARMADO?','2' => '2. MADERA?','3' => '3. TEJAS?','4' => '4. PLANCHAS DE CALAMINA, FIBRA DE CEMENTO O SIMILARES?','5' => '5. CAñA O ESTERA CON TORTA DE BARRO O CEMENTO?','6' => '6. TRIPLAY / ESTERA / CARRIZO?','7' => '7. PAJA, HOJA DE PALMERA Y SIMILARES?','8' => '8. OTRO MATERIAL?'))
,array('C2_P4_O', 'render' => TRUE, 'type' => 'TEXT', 'length' => '15')
,array('C2_P5', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'dropdown'=>TRUE, 'options'=>array('' => 'SELECCIONE','1' => '1. PARQUET O MADERA PULIDA?','2' => '2. LáMINAS ASFáLTICAS, VINíLICOS O SIMILARES?','3' => '3. LOSETAS, TERRAZOS CERáMICOS O SIMILARES?','4' => '4. MADERA (PONA, TORNILLO, ETC)?','5' => '5. CEMENTO?','6' => '6. TIERRA?','7' => '7. OTRO MATERIAL?'))
,array('C2_P5_O', 'render' => TRUE, 'type' => 'TEXT', 'length' => '15')
,array('C2_P6', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'dropdown'=>TRUE, 'options'=>array('' => 'SELECCIONE','1' => '1. RED PúBLICA DENTRO DE LA VIVIENDA?','2' => '2. RED PúBLICA FUERA DE LA VIVIENDA PERO DENTRO DE LA EDIFICACIóN, LOTE O TERRENO?','3' => '3. PILóN DE USO PúBLICO?','4' => '4. CAMIóN - CISTERNA U OTRO SIMILAR?','5' => '5. POZO (AGUA DE SUBSUELO)?','6' => '6. RíO, ACEQUIA, MANANTIAL O SIMILAR?','7' => '7. OTRO?'))
,array('C2_P6_O', 'render' => TRUE, 'type' => 'TEXT', 'length' => '15')
,array('C2_P7', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'radio'=>TRUE, 'options'=>array('1' => '1. SI','2' => '2. NO'))
,array('C2_P8', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'radio'=>TRUE, 'options'=>array('1' => '1. SI','2' => '2. NO'))
,array('C2_P8A', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '2')
,array('C2_P8B', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1')
,array('C2_P8C', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '2')
,array('C2_P9', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'dropdown'=>TRUE, 'options'=>array('' => 'SELECCIONE','1' => '1. RED PúBLICA DE DESAGüE DENTRO DE LA VIVIENDA?','2' => '2. RED PúBLICA DE DESAGüE FUERA DE LA VIVIENDA, PERO DENTRO DE LA EDIFICACIóN, LOTE O TERRENO?','3' => '3. LETRINA?','4' => '4. POZO SéPTICO?','5' => '5. POZO CIEGO O NEGRO?','6' => '6. RíO, ACEQUIA, CANAL O SIMILAR?','7' => '7. OTRO?'))
,array('C2_P9_O', 'render' => TRUE, 'type' => 'TEXT', 'length' => '15')
,array('C2_P10_1', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'checkbox'=>TRUE, 'options'=>array( '1' => '1. Red pública?'))
,array('C2_P10_2', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'checkbox'=>TRUE, 'options'=>array( '1' => '2, Generador eléctrico / grupo electrógeno?'))
,array('C2_P10_3', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'checkbox'=>TRUE, 'options'=>array( '1' => '3, Panel solar?'))
,array('C2_P10_4', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'checkbox'=>TRUE, 'options'=>array( '1' => '4, Otro?'))
,array('C2_P10_5', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'checkbox'=>TRUE, 'options'=>array( '1' => '5, NO TIENE'))
,array('C2_P10_O', 'render' => TRUE, 'type' => 'TEXT', 'length' => '15')
,array('C2_P11', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '2')
,array('C2_P12', 'render' => TRUE, 'type' => 'INTEGER', 'length' => '1', 'dropdown'=>TRUE, 'options'=>array('' => 'SELECCIONE','1' => '1. ¿ALQUILADA?','2' => '2. ¿PROPIA POR INVASIóN?','3' => '3. ¿PROPIA, PAGáNDOLA A PLAZOS?','4' => '4. ¿PROPIA TOTALMENTE PAGADA?','5' => '5. ¿CEDIDA POR EL CENTRO DE TRABAJO?','6' => '6. ¿CEDIDA POR OTRO HOGAR?','7' => '7. ¿CEDIDA POR UNA INSTITUCIóN?','8' => '8. ¿OTRA FORMA?'))
,array('C2_P12_O', 'render' => TRUE, 'type' => 'TEXT', 'length' => '15')
,);
        }
        
        public function getRules(){
            return array(array('UBIGEO', 'required' => TRUE, 'regex' => '(010101:250402)' )
,array('ZONA', 'required' => TRUE, 'regex' => '(00100:30010)' )
,array('SECCION', 'required' => TRUE, 'regex' => '(001:998)' )
,array('MANZANA', 'required' => TRUE, 'regex' => '(0:9) (A:Z)' )
,array('ESTADO_ENVIO', 'required' => TRUE, 'regex' => '(1:2)' )
,array('AREA', 'required' => TRUE, 'regex' => '(1:2)' )
,array('ID', 'required' => TRUE, 'regex' => '(0000001:9999998)' )
,array('VIVIENDA', 'required' => TRUE, 'regex' => '(0001:9999)' )
,array('CCDD', 'required' => TRUE, 'regex' => '(01:25)' )
,array('NOMBREDD', 'required' => TRUE, 'regex' => '(A:Z)' )
,array('CCPP', 'required' => TRUE, 'regex' => '(01:20)' )
,array('NOMBREPV', 'required' => TRUE, 'regex' => '(A:Z)' )
,array('CCDI', 'required' => TRUE, 'regex' => '(01:43), 99' )
,array('NOMBREDI', 'required' => TRUE, 'regex' => '(A:Z)' )
,array('CODCCPP', 'required' => TRUE, 'regex' => '(0001:9998)' )
,array('NOMCCPP', 'required' => TRUE, 'regex' => '(A:Z), (0:9)' )
,array('ZONA_ID', 'required' => TRUE, 'regex' => '(001:300)' )
,array('ZONA_A', 'required' => TRUE, 'regex' => '(A:Z)' )
,array('SECCION_U', 'required' => TRUE, 'regex' => '(001:998)' )
,array('AEU', 'required' => TRUE, 'regex' => '(001:998)' )
,array('MANZANA_ID', 'required' => TRUE, 'regex' => '(001:200)' )
,array('MANZANA_A', 'required' => TRUE, 'regex' => '(A:Z)' )
,array('FRENTE', 'required' => TRUE, 'regex' => '(1:50)' )
,array('SECCION_R', 'required' => TRUE, 'regex' => '(001:998)' )
,array('AER_INI', 'required' => TRUE, 'regex' => '(001:150)' )
,array('AER_FIN', 'required' => TRUE, 'regex' => '(001:150)' )
,array('TIPVIA', 'required' => TRUE, 'regex' => '(1:6 )' )
,array('NOMVIA', 'required' => TRUE, 'regex' => '(A:Z), (0:9), SN' )
,array('NROPTA', 'required' => FALSE, 'regex' => '(0:9), (A:Z), SN' )
,array('NROPTA_ALF', 'required' => FALSE, 'regex' => '(A:Z), (0:9)' )
,array('BLOCK', 'required' => FALSE, 'regex' => '(0:9), (A:Z), SN' )
,array('INTERIOR', 'required' => FALSE, 'regex' => '(0:9), (A:Z), SN' )
,array('INTERIOR_ALF', 'required' => FALSE, 'regex' => '(A:Z), (0:9)' )
,array('PISO', 'required' => FALSE, 'regex' => '(1:30) A,S,(S1:S2),M' )
,array('MZA', 'required' => FALSE, 'regex' => '(0:9), (A:Z), SN' )
,array('LOTE', 'required' => FALSE, 'regex' => '(0:9), (A:Z), SN' )
,array('KM', 'required' => FALSE, 'regex' => '(1:1000)' )
,array('GPS_LONG', 'required' => TRUE, 'regex' => '[SEGÚN GPS]' )
,array('GPS_LATI', 'required' => TRUE, 'regex' => '[SEGÚN GPS]' )
,array('THOGAR', 'required' => TRUE, 'regex' => '(1:50)' )
,array('HOGAR', 'required' => TRUE, 'regex' => '(1:50)' )
,array('C2_P1', 'required' => TRUE, 'regex' => '(1:18)' )
,array('C2_P1_O', 'required' => TRUE, 'regex' => '(A:Z), (0:9)' )
,array('C2_P2', 'required' => TRUE, 'regex' => '(1:7)' )
,array('C2_P3', 'required' => TRUE, 'regex' => '(1:9)' )
,array('C2_P3_O', 'required' => TRUE, 'regex' => '(A:Z)' )
,array('C2_P4', 'required' => TRUE, 'regex' => '(1:8)' )
,array('C2_P4_O', 'required' => TRUE, 'regex' => '(A:Z)' )
,array('C2_P5', 'required' => TRUE, 'regex' => '(1:7)' )
,array('C2_P5_O', 'required' => TRUE, 'regex' => '(A:Z)' )
,array('C2_P6', 'required' => TRUE, 'regex' => '(1:7)' )
,array('C2_P6_O', 'required' => TRUE, 'regex' => '(A:Z)' )
,array('C2_P7', 'required' => TRUE, 'regex' => '(1:2)' )
,array('C2_P8', 'required' => TRUE, 'regex' => '(1:2)' )
,array('C2_P8A', 'required' => TRUE, 'regex' => '(1:24)' )
,array('C2_P8B', 'required' => TRUE, 'regex' => '(1:6)' )
,array('C2_P8C', 'required' => TRUE, 'regex' => '(1:24)' )
,array('C2_P9', 'required' => TRUE, 'regex' => '(1:7)' )
,array('C2_P9_O', 'required' => TRUE, 'regex' => '(A:Z)' )
,array('C2_P10_1', 'required' => TRUE, 'regex' => '(0:1)' )
,array('C2_P10_2', 'required' => TRUE, 'regex' => '(0:1)' )
,array('C2_P10_3', 'required' => TRUE, 'regex' => '(0:1)' )
,array('C2_P10_4', 'required' => TRUE, 'regex' => '(0:1)' )
,array('C2_P10_5', 'required' => TRUE, 'regex' => '(0:1)' )
,array('C2_P10_O', 'required' => TRUE, 'regex' => '(A:Z)' )
,array('C2_P11', 'required' => TRUE, 'regex' => '(1:35)' )
,array('C2_P12', 'required' => TRUE, 'regex' => '(1:8)' )
,array('C2_P12_O', 'required' => TRUE, 'regex' => '(A:Z)' )
,);
        }
        
        public function tablename(){
            return 'TB_I_VIVIENDA';
        }
     
}